version: "3"

services:
  database:
      build: .
      image: "fariasbrunobrn/postgres-fully-extension:latest"
      environment:
        POSTGRES_USER: app_user
        POSTGRES_PASSWORD: powerfull_password
        POSTGRES_DB: app_database
      ports:
        - 5432:5432
volumes:
  database:
